In [2]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
## style of matplotlib
plt.style.use("fivethirtyeight")

In [17]:
class Perceptron:
    def __init__(self, learning_rate: float=None, epochs: int=None):
        # weights should me much more smaller we multiply by 1e because it- 
        # helps to converge faster
        #1e-4 is 10 raise to the power of -4
        self.weights = np.random.randn(3) *1e-4
        self.learning_rate = learning_rate
        self.epochs = epochs #no. of iterations
        
    ## we are using _ for _z_outcome at start becoz it is a hidden method/private method    
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1,0)
    
        
    def fit(self, X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")
        
        
        for epoch in range(self.epochs):
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            self.error = self.y - y_hat
            ## the weight update rule
            self.weights = self.weights + self.learning_rate * np.dot(X_with_bias.T, self.error)
            
    def predict(self, X):
        ## It will only have forward pass
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
        

In [6]:
obj = Perceptron(learning_rate = 0.01, epochs = 10)
obj.learning_rate

0.01

In [7]:
obj.epochs

10

In [9]:
obj.weights

array([8.46792744e-05, 1.78859270e-05, 6.16262108e-05])

## OR GATE

In [18]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)

df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [19]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X, y

In [20]:
X, y = prepare_data(df_OR)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [21]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [22]:
X, y = prepare_data(df_OR)

learning_rate = 0.1
epochs = 10

model_OR = Perceptron(learning_rate = learning_rate,epochs = epochs)

model_OR.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]


In [25]:
model_OR.predict(X=[[1,0]])

array([1])